config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/sign-up' => 'devise/registrations#new'
    get  '/sign-in' => 'devise/sessions#new'
    get  '/sign-out' => 'devise/sessions#destroy'
  end

  root   'books#home'
  get    '/shop', to: 'books#index'
  get    '/shop/:category_id', to: 'books#index', as: 'shop_category'
  resources :books, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resource  :cart, only: [:create, :show, :update, :destroy] do
    delete ':item_id', action: 'remove_item', as: 'item', item_id: /[0-9]+/
  end
  resources :checkout, only: [:show, :update]
  resource  :user, only: [:edit, :destroy] do
    put 'address',  action: 'address'
    put 'email',    action: 'email'
    put 'password', action: 'password'
  end
  resources :orders, only: [:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  mount_uploader :photo, PhotoUploader
  has_many :orders, dependent: :nullify
  has_many :reviews, dependent: :destroy
  has_many :credit_cards, dependent: :destroy
  has_many :addresses, dependent: :nullify
  validates :email, presence: true, uniqueness: true
  #accepts_nested_attributes_for :credit_cards

  belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'

  def self.find_for_facebook_oauth(auth)
    if user = User.find_by(email: auth.info.email)
      user
    else
      User.create(email: auth.info.email, password: Devise.friendly_token[0,20])
    end
  end

  def name
    email.split('@').first
  end

  def save_address(address_params = {})
    address_index = (address_params[:type]+'_address').to_sym
    address_params.delete(:type)
    address = self.send(address_index)
    if (address.nil? || self.billing_address_id == self.shipping_address_id || address.used_in_placed_orders?)
      address = Address.find_or_create_by(address_params)
      address.valid? && self.update(address_index => address)
    else
      address.update(address_params)
    end
  end

  def order_in_progress
    self.orders.find_or_create_by(:state => Order::STATE_IN_PROGRESS)
  end

  def placed_orders
    self.orders.not_in_progress.order(state: :asc, completed_at: :desc)
  end

  def last_placed_order
    self.orders.not_in_progress.order(completed_at: :desc, id: :desc).first
  end

  def last_credit_card
    self.credit_cards.order('id DESC').first
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth request.env['omniauth.auth']
    if user.persisted?
      set_flash_message(:notice, :success, :kind => 'Facebook')
      sign_in_and_redirect user, :event => :authentication
    else
      set_flash_message(:notice, :failure, :kind => 'Facebook', reason: '!?')
      redirect_to sign_in_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CommonInForms
  before_action :require_login, :set_data

  # GET /user/edit
  def edit
    @billing_address  ||= @user.billing_address  || Address.new
    @shipping_address ||= @user.shipping_address || Address.new
    render :edit
  end

  # PUT /user/update_email
  def email
    if @user.update(user_params)
      redirect_to edit_user_path, :notice => 'Your e-mail was updated.'
    else
      set_errors_for 'user', 'email'
      edit
    end
  end

  # PUT /user/update_password
  def password
    if @user.update_with_password(user_params)
      redirect_to edit_user_path, :notice => 'Your password was updated.'
    else
      set_errors_for 'user', 'password'
      edit
    end
  end

  # PUT /user/save_address
  def address
    type = params[:type] || 'billing'
    if @user.save_address(address_params(type).merge(type: type))
      redirect_to edit_user_path, :notice => 'Your '+type+' address was updated.'
    else
      instance_variable_set("@#{type}_address", Address.new(address_params(type)))
      set_errors_for 'user', type+'_address'
      edit
    end
  end

  # DELETE /user
  def destroy
    if params.has_key?(:remove_account_confirm)
      @user.destroy
      redirect_to root_path
    else
      redirect_to edit_user_path, :notice => 'You should confirm your action!'
    end
  end

  private
  def set_data
    @user = current_user
    @errors = {}
  end

  def user_params
    params.require(:user).permit(:email, :current_password, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<div class="settings clearfix">
    <h1>Settings</h1>
    <div class="row">
        <div class="col-md-6">
            <h2>BILLING ADDRESS</h2>
            <%= form_tag(address_user_path, :method => 'put') do %>
                <%= render 'shared/errors', area: 'billing_address' %>
                <%= render 'shared/addr_form', type: 'billing', address: @billing_address %>
                <%= submit_tag('SAVE', :class => 'btn btn-default') %>
            <% end %>
        </div>
        <div class="col-md-6">
            <h2>SHIPPING ADDRESS</h2>
            <%= form_tag(address_user_path, :method => 'put') do %>
                <%= render 'shared/errors', area: 'shipping_address' %>
                <%= render 'shared/addr_form', type: 'shipping', address: @shipping_address %>
                <%= submit_tag('SAVE', :class => 'btn btn-default') %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2>E-MAIL</h2>
            <%= form_tag(email_user_path, :method => 'put') do %>
                <%= render 'shared/errors', area: 'email' %>
                <div class="form-group">
                    <%= email_field_tag('user[email]', @user.email, :class => 'form-control', :placeholder => 'Enter email')%>
                </div>
                <%= submit_tag('SAVE', :class => 'btn btn-default') %>
            <% end %>
        </div>
        <div class="col-md-6">
            <h2>PASSWORD</h2>
            <%= form_tag(password_user_path, :method => 'put', :autocomplete => 'off') do %>
                <%= render 'shared/errors', area: 'password' %>
                <div class="form-group">
                    <%= label_tag('user[current_password]', 'Current password')%>
                    <%= password_field_tag('user[current_password]', '', :class => 'form-control', :placeholder => 'Type current password') %>
                </div>
                <div class="form-group">
                    <%= label_tag('user[password]', 'New password')%>
                    <%= password_field_tag('user[password]', '', :class => 'form-control', :placeholder => 'Type new password') %>
                </div>
                <div class="form-group">
                    <%= label_tag('user[password_confirmation]', 'New password confirmation')%>
                    <%= password_field_tag('user[password_confirmation]', '', :class => 'form-control', :placeholder => 'Type new password confirmation') %>
                </div>
                <%= submit_tag('SAVE', :class => 'btn btn-default') %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>REMOVE ACCOUNT</h2>
            <%= form_tag(user_path, :method => 'delete', :class => 'form-inline') do %>
                <div class="alert_message">You must confirm that you understand the consequences of your action!</div>
                <%= submit_tag('REMOVE ACCOUNT', :class => 'btn btn-default', :id => 'remove_account') %>
                <div class="checkbox">
                    <label><%= check_box_tag('remove_account_confirm') %> I understand that all data will be lost</label>
                </div>
            <% end %>
        </div>
    </div>
</div>