config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/sign-up' => 'devise/registrations#new'
    get  '/sign-in' => 'devise/sessions#new'
    get  '/sign-out' => 'devise/sessions#destroy'
  end

  root   'books#home'
  get    '/shop', to: 'books#index'
  get    '/shop/:category_id', to: 'books#index', as: 'shop_category'
  resources :books, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resource  :cart, only: [:create, :show, :update, :destroy] do
    delete ':item_id', action: 'remove_item', as: 'item', item_id: /[0-9]+/
  end
  resources :checkout, only: [:show, :update]
  resource  :user, only: [:edit, :destroy] do
    put 'address',  action: 'address'
    put 'email',    action: 'email'
    put 'password', action: 'password'
  end
  resources :orders, only: [:index, :show]

end

app/models/order.rb
class Order < ActiveRecord::Base
  STATES = %w(in_progress in_queue in_delivery delivered canceled)
  STATE_IN_PROGRESS = 'in_progress'

  include AASM

  has_many :order_items, dependent: :destroy
  belongs_to :user
  belongs_to :credit_card
  belongs_to :shipping_method
  belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'

  validates :number, uniqueness: true
  validates :shipping_cost, numericality: {:greater_than_or_equal_to => 0}, allow_blank: true
  validates :state, :user, presence: true

  scope :not_in_progress, -> { where.not(state: STATE_IN_PROGRESS) }

  enum state: STATES
  aasm :column => :state, :enum => true, :whiny_transitions => false do
    state :in_progress, :initial => true
    state :in_queue
    state :in_delivery
    state :delivered
    state :canceled

    event :checkout, :before => :set_completed_at, :after => :update_sold_count do
      transitions :from => :in_progress, :to => :in_queue
    end
    event :confirm do
      transitions :from => :in_queue, :to => :in_delivery
    end
    event :cancel do
      transitions :from => :in_queue, :to => :canceled
    end
    event :deliver do
      transitions :from => :in_delivery, :to => :delivered
    end
  end

  after_create do |order|
    begin
    end while !order.update(number: rand(100000000..999999999))
  end

  def add_book(book, quantity)
    order = self
    order_item = order.order_items.find_by(:book => book)
    if order_item.nil?
      order_item = OrderItem.new({:book => book, :order => order, :price => book.price, :quantity => quantity})
    else
      order_item.quantity += quantity
    end
    order_item.save
  end

  def save_credit_card(credit_card_params = {})
    credit_card = self.credit_card
    if (credit_card.nil? || credit_card.used_in_placed_orders?)
      credit_card = CreditCard.find_or_create_by(credit_card_params)
      credit_card.valid? && self.update(:credit_card => credit_card)
    else
      credit_card.update(credit_card_params)
    end
  end

  def status
    I18n.t("order.states.#{self.state}")
  end

  def display_number
    'R'+self.number.to_s
  end

  def total_price
    @total_price = self.order_items.sum('quantity*price') if @total_price.nil?
    @total_price
  end

  def total_items
    @total_items = self.order_items.sum(:quantity) if @total_items.nil?
    @total_items
  end

  def books
    self.order_items.includes(:book).references(:book)
  end

  protected
  def set_completed_at
    self.completed_at = Time.zone.now
  end

  def update_sold_count
    return false if self.state == STATE_IN_PROGRESS
    self.order_items.each do |item|
      Book.where(id: item.book_id).update_all("sold_count = sold_count + #{item.quantity}")
    end
    return true
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login

  # GET /orders
  def index
    @order = current_order
    @order_items = @order.books
    @orders = current_user.placed_orders
  end

  # GET /orders/1
  def show
    @order = current_user.orders.find(params[:id])
    @order_items = @order.books
    @order_total = @order.total_price+@order.shipping_cost
  end
end

app/views/orders/cart.html.erb
<div class="cart clearfix">
    <%- if @cart_items.length > 0 %>
        <%= form_tag(cart_update_path, :method => 'put') do %>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th colspan="2">BOOK</th>
                    <th>PRICE</th>
                    <th>QTY</th>
                    <th>TOTAL</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            <%- @cart_items.each do |item| %>
            <tr>
                <td><%= link_to(image_tag(item.book.image.thumb, :alt => item.book.title), book_path(item.book)) %></td>
                <td>
                    <div><%= item.book.title %></div>
                    <p><%= item.book.short_description %></p>
                </td>
                <td class="price">$<%= item.price %></td>
                <td><%= number_field_tag('quantity['+item.id.to_s+']', item.quantity, {:min => 1, :max => 20, :class => 'form-control quantity'}) %></td>
                <td class="price">$<%= number_with_precision(item.price*item.quantity, precision: 2) %></td>
                <td class="price remove"><%= link_to('&times;'.html_safe, cart_remove_path(item.id), {:method => 'delete'}) %></td>
            </tr>
            <%- end %>
            </tbody>
        </table>
        <div class="clearfix">
            <div class="subtotal pull-right">SUBTOTAL: &nbsp; <strong>$<%= number_with_precision(@subtotal, precision: 2) %></strong></div>
        </div>
        <div class="form-inline pull-right">
            <input type="text" class="form-control" placeholder="Coupon code" size="12">
            <%= submit_tag('UPDATE', :class => 'btn btn-default') %>
            <input class="btn btn-default" type="button" value="CHECKOUT">
        </div>
        <%= link_to('EMPTY CART', cart_empty_path, {:class => 'btn btn-default', :method => 'delete'}) %>
        <%= link_to('CONTINUE SHOPPING', shop_path, {:class => 'btn btn-default'}) %>
        <%- end %>
    <%- else %>
        <p>Shopping cart is empty... <%= link_to 'Get started shopping!', shop_path %></p>
    <%- end %>
</div>

app/views/orders/index.html.erb
<div class="orders clearfix">
    <h1>Orders</h1>
    <h2>In progress</h2>
    <%- unless @order_items.blank? %>
    <div class="order">
        <%= render 'shared/order', order_items: @order_items %>
        <div class="clearfix">
            <div class="subtotal pull-right">SUBTOTAL: &nbsp; <strong><%= number_to_currency(@order.total_price) %></strong></div>
            <%= link_to 'GO TO CART', cart_path, class: 'btn btn-default' %>
        </div>
    </div>
    <%- else %>
      <p>Order is empty&hellip; <%= link_to 'Get started shopping!', shop_path %></p>
    <%- end %>
    <div>&nbsp;</div>
<%- unless (@orders.nil?) %>
    <%- previous_state = '' %>
    <%- @orders.each do |order| %>
      <%- if previous_state != order.state %>
        <%- if previous_state != '' %>
    </tbody>
    </table>
        <%- end %>
    <h2><%= order.status.upcase %></h2>
    <table class="table table-condensed no-borders">
      <thead>
        <tr>
          <th width="40%">NUMBER</th>
          <th width="30%">COMPLETED&nbsp;AT</th>
          <th width="20%">TOTAL</th>
          <th width="10%">&nbsp;</th>
        </tr>
      </thead>
    <tbody>
      <%- end %>
      <tr>
        <td><%= order.display_number %></td>
        <td><%= date_format(order.completed_at) %></td>
        <td><%= number_to_currency(order.total_price+order.shipping_cost) %></td>
        <td><%= link_to 'View', order_path(order) %></td>
      </tr>
    <%- previous_state = order.state %>
    <%- end %>
    </tbody>
    </table>
<%- end %>
</div>

app/views/orders/show.html.erb
<div class="clearfix">
    <div class="order-back"> <%= link_to '<< Back to orders', orders_path %></div>
    <h1 class="pull-left">Order <%= @order.display_number %></h1>
    <div class="order-status"> &nbsp; <%= @order.status %></div>
</div>
<div class="order clearfix">
<%- unless @order_items.blank? %>
    <%= render 'shared/order', order_items: @order_items %>
    <div class="clearfix">
        <div class="pull-right">
            <div class="subtotal clearfix">
                <div class="pull-right"><strong><%= number_to_currency(@order.total_price) %></strong><br /><strong><%= number_to_currency(@order.shipping_cost) %></strong></div>
                <div class="pull-right">SUBTOTAL: &nbsp; <br />SHIPPING: &nbsp; </div>
            </div>
        </div>
    </div>
    <div class="clearfix total">
        <div class="pull-right subtotal">
            ORDER TOTAL: &nbsp; <strong><%= number_to_currency(@order_total) %></strong>
        </div>
    </div>
<%- else %>
    <p>Order is empty&hellip;</p>
<%- end %>
</div>