config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/sign-up' => 'devise/registrations#new'
    get  '/sign-in' => 'devise/sessions#new'
    get  '/sign-out' => 'devise/sessions#destroy'
  end

  root   'books#home'
  get    '/shop', to: 'books#index'
  get    '/shop/:category_id', to: 'books#index', as: 'shop_category'
  resources :books, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resource  :cart, only: [:create, :show, :update, :destroy] do
    delete ':item_id', action: 'remove_item', as: 'item', item_id: /[0-9]+/
  end
  resources :checkout, only: [:show, :update]
  resource  :user, only: [:edit, :destroy] do
    put 'address',  action: 'address'
    put 'email',    action: 'email'
    put 'password', action: 'password'
  end
  resources :orders, only: [:index, :show]

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login, :set_order

  # GET /cart
  def show
    @cart_items = @order.books
  end

  # DELETE /cart
  def destroy
    @order.order_items.destroy_all
    redirect_to cart_path
  end

  # DELETE /cart/:item_id
  def remove_item
    @order.order_items.find(params[:item_id]).destroy
    redirect_to cart_path
  end

  # POST /cart
  def create
    @order.add_book(Book.find(params[:book_id].to_i), params[:quantity].to_i)
    redirect_to :back, :notice => 'Book was successfully added to cart.'
  end

  # PUT /cart
  def update
    params[:quantity].each do |item_id, quantity|
      @order.order_items.find_by(id: item_id).update(:quantity => quantity)
    end
    redirect_to cart_path, :notice => 'Cart was successfully updated.'
  end

  private
  def set_order
    @order = current_order
  end
end

app/views/carts/checkout1.html.erb
<div class="checkout clearfix">
    <div class="stages">
        <span>ADDRESS</span> &nbsp; SHIPPING &nbsp; PAYMENT &nbsp; CONFIRM &nbsp; COMPLETE
    </div>
    <h1>Checkout</h1>
    <%= form_tag(cart_path, :method => 'put') do %>
    <div class="row">
        <div class="col-md-4">
            <h2>BILLING ADDRESS</h2>
            <%= render 'shared/errors', area: 'billing_address' %>
            <%= render 'shared/addr_form', type: 'billing', address: @billing_address %>
        </div>
        <div class="col-md-4">
            <h2>SHIPPING ADDRESS</h2>
            <div id="shipping_address">
                <%= render 'shared/errors', area: 'shipping_address' %>
                <%= render 'shared/addr_form', type: 'shipping', address: @shipping_address %>
            </div>
            <div class="checkbox">
                <label><%= check_box_tag('use_billing_address', 1, (!@order.billing_address_id.nil? && @order.billing_address_id==@order.shipping_address_id)) %> Use billing address</label>
            </div>
        </div>
        <div class="col-md-4">
            <div class="pull-right">
                <h2>ORDER SUMMARY</h2>
                <div class="summary-price">
                    $<%= @order.total_price %><br />$<%= @order.total_price %>
                </div>
                <div class="summary-title">
                    <nobr>ITEMS TOTAL:</nobr><br /><nobr>ORDER TOTAL:</nobr>
                </div>
            </div>
        </div>
    </div>
    <div>
        <%= button_tag('SAVE AND CONTINUE', :class => 'btn btn-default', :type => 'submit', :name => 'address') %>
        <%- unless @order.billing_address_id.nil? || @order.shipping_address_id.nil? %>
            <%= link_to('CONTINUE', cart_checkout_path(2), {:class => 'btn btn-default checkout'}) %>
        <%- end %>
    </div>
    <% end %>
</div>

app/views/carts/checkout2.html.erb
<div class="checkout clearfix">
    <div class="stages">
      <%= link_to('ADDRESS', cart_checkout_path) %> &nbsp; <span>SHIPPING</span> &nbsp; PAYMENT &nbsp; CONFIRM &nbsp; COMPLETE
    </div>
    <h1>Checkout</h1>
    <%= form_tag(cart_path, :method => 'put') do %>
    <div class="row">
        <div class="col-md-4">
            <h2>SHIPPING METHOD</h2>
            <%- if @shipping_methods.blank? %>
                There are no shipping methods active.
            <%- else %>
                <%= render 'shared/errors', area: 'shipping_method' %>
                <%= hidden_field_tag('shipping_cost', @shipping_method.cost) %>
                <% @shipping_methods.each do |shipping| %>
                <div class="radio">
                    <label>
                        <%= hidden_field_tag("shipping_method_id_#{shipping.id}", shipping.cost) %>
                        <%= radio_button_tag('shipping_method_id', shipping.id, shipping.id==@shipping_method.id) %>
                        <%= shipping.name %> + $<%= shipping.cost %>
                    </label>
                </div>
                <%- end %>
            <%- end %>
        </div>
        <div class="col-md-4">
            &nbsp;
        </div>
        <div class="col-md-4">
            <div class="pull-right">
                <h2>ORDER SUMMARY</h2>
                <div class="summary-price">
                    $<span id="checkout_items_total"><%= @order.total_price %></span><br />
                    $<span id="checkout_shipping"><%= @shipping_method.cost %></span><br />
                    $<span id="checkout_order_total"><%= (@order.total_price+@shipping_method.cost) %></span>
                </div>
                <div class="summary-title">
                    <nobr>ITEMS TOTAL:</nobr><br />
                    <nobr>SHIPPING:</nobr><br />
                    <nobr>ORDER TOTAL:</nobr>
                </div>
            </div>
        </div>
    </div>
    <div>
        <%= button_tag('SAVE AND CONTINUE', :class => 'btn btn-default', :type => 'submit', :name => 'shipping') %>
        <%- unless @order.shipping_method_id.nil? %>
            <%= link_to('CONTINUE', cart_checkout_path(3), {:class => 'btn btn-default checkout'}) %>
        <%- end %>
    </div>
    <% end %>
</div>

app/views/carts/checkout3.html.erb
<div class="checkout clearfix">
    <div class="stages">
        <%= link_to('ADDRESS', cart_checkout_path) %> &nbsp; <%= link_to('SHIPPING', cart_checkout_path(2)) %> &nbsp; <span>PAYMENT</span> &nbsp; CONFIRM &nbsp; COMPLETE
    </div>
    <h1>Checkout</h1>
    <%= form_tag(cart_path, :method => 'put') do %>
    <div class="row">
        <div class="col-md-4">
            <h2>CARD DETAILS</h2>
            <%= render 'shared/errors', area: 'credit_card' %>
            <div class="form-group">
                <%= text_field_tag('credit_card[number]', @credit_card.number, :class => 'form-control', :placeholder => 'Card Number') %>
            </div>
            <div class="form-group">
                Expiration date:
                <div class="month-year">
                    <div class="input-group">
                        <div class="input-group-addon">Month</div>
                        <%= select_tag('credit_card[expiration_month]', options_for_select(@credit_card.month_list, @credit_card.expiration_month), :class => 'form-control month')%>
                    </div>
                    <div class="input-group">
                        <div class="input-group-addon">Year</div>
                        <%= select_tag('credit_card[expiration_year]', options_for_select(@credit_card.year_list, @credit_card.expiration_year), :class => 'form-control year')%>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group card-code">
                    <div class="input-group-addon">Card code:</div>
                    <%= password_field_tag('credit_card[code]', @credit_card.code, :class => 'form-control') %>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            &nbsp;
        </div>
        <div class="col-md-4">
            <div class="pull-right">
                <h2>ORDER SUMMARY</h2>
                <div class="summary-price">
                    $<%= @order.total_price %><br />$<%= @order.shipping_cost %><br />$<%= (@order.total_price+@order.shipping_cost) %>
                </div>
                <div class="summary-title">
                    <nobr>ITEMS TOTAL:</nobr><br />
                    <nobr>SHIPPING:</nobr><br />
                    <nobr>ORDER TOTAL:</nobr>
                </div>
            </div>
        </div>
    </div>
    <div>
        <%= button_tag('SAVE AND CONTINUE', :class => 'btn btn-default', :type => 'submit', :name => 'payment') %>
        <%- unless @order.credit_card_id.nil? %>
            <%= link_to('CONTINUE', cart_checkout_path(4), {:class => 'btn btn-default checkout'}) %>
        <%- end %>
    </div>
    <% end %>
</div>

app/views/carts/checkout4.html.erb
<div class="checkout clearfix">
    <div class="stages">
        <%= link_to('ADDRESS', cart_checkout_path) %> &nbsp; <%= link_to('SHIPPING', cart_checkout_path(2)) %> &nbsp; <%= link_to('PAYMENT', cart_checkout_path(3)) %> &nbsp; <span>CONFIRM</span> &nbsp; COMPLETE
    </div>
    <h1>Checkout</h1>
    <div class="row">
        <div class="col-md-3">
            <div class="edit"><%= link_to('(edit)', cart_checkout_path) %></div>
            <h2>Shipping Address</h2>
            <%= render 'shared/addr_details', address: @shipping_address %>
        </div>
        <div class="col-md-3">
            <div class="edit"><%= link_to('(edit)', cart_checkout_path) %></div>
            <h2>Billing Address</h2>
            <%= render 'shared/addr_details', address: @billing_address %>
        </div>
        <div class="col-md-3">
            <div class="edit"><%= link_to('(edit)', cart_checkout_path(2)) %></div>
            <h2>Shipping method</h2>
            <div class="details">
                <%= @order.shipping_method.name %>
            </div>
        </div>
        <div class="col-md-3">
            <div class="edit"><%= link_to('(edit)', cart_checkout_path(3)) %></div>
            <h2>Payment information</h2>
            <div class="details">
                <%= @credit_card.display_number %><br />
                <%= @credit_card.display_month %>/<%= @credit_card.expiration_year %>
            </div>
        </div>
    </div>
</div>
<div class="order clearfix">
    <%= render 'shared/order' %>
    <div class="clearfix">
        <div class="pull-right">
            <div class="subtotal clearfix">
                <div class="pull-right"><strong>$<%= @order.total_price %></strong><br /><strong>$<%= @order.shipping_cost %></strong></div>
                <div class="pull-right">SUBTOTAL: &nbsp; <br />SHIPPING: &nbsp; </div>
            </div>
        </div>
    </div>
    <div class="clearfix total">
        <div class="pull-right subtotal">
            ORDER TOTAL: &nbsp; <strong>$<%= (@order.total_price+@order.shipping_cost) %></strong>
        </div>
    </div>
    <%= form_tag(cart_path, :method => 'put') do %>
        <%= button_tag('PLACE ORDER', :class => 'btn btn-default', :type => 'submit', :name => 'confirm') %>
    <% end %>
</div>

app/views/carts/checkout5.html.erb
<div class="checkout clearfix">
    <h1>Order <%= @order.display_number %></h1>
    <div class="row">
        <div class="col-md-3">
            <h2>Shipping Address</h2>
            <%= render 'shared/addr_details', address: @shipping_address %>
        </div>
        <div class="col-md-3">
            <h2>Billing Address</h2>
            <%= render 'shared/addr_details', address: @billing_address %>
        </div>
        <div class="col-md-3">
            <h2>Shipping method</h2>
            <div class="details">
              <%= @order.shipping_method.name %>
            </div>
        </div>
        <div class="col-md-3">
            <h2>Payment information</h2>
            <div class="details">
              <%= @credit_card.display_number %><br />
              <%= @credit_card.display_month %>/<%= @credit_card.expiration_year %>
            </div>
        </div>
    </div>
</div>
<div class="order clearfix">
    <%= render 'shared/order' %>
    <div class="clearfix">
        <div class="pull-right">
            <div class="subtotal clearfix">
                <div class="pull-right"><strong>$<%= @order.total_price %></strong><br /><strong>$<%= @order.shipping_cost %></strong></div>
                <div class="pull-right">SUBTOTAL: &nbsp; <br />SHIPPING: &nbsp; </div>
            </div>
        </div>
    </div>
    <div class="clearfix total">
        <div class="pull-right subtotal">
            ORDER TOTAL: &nbsp; <strong>$<%= (@order.total_price+@order.shipping_cost) %></strong>
        </div>
    </div>
    <%= link_to('GO BACK TO STORE', shop_path, {:class => 'btn btn-default'}) %>
</div>

app/views/carts/show.html.erb
<div class="cart clearfix">
    <%- unless @cart_items.blank? %>
        <%= form_tag(cart_path, :method => 'put') do %>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th colspan="2">BOOK</th>
                    <th>PRICE</th>
                    <th>QTY</th>
                    <th>TOTAL</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            <%- @cart_items.each do |item| %>
            <tr>
                <td><%= link_to(image_tag(item.book.image.thumb, :alt => item.book.title), book_path(item.book)) %></td>
                <td>
                    <div><%= item.book.title %></div>
                    <p><%= item.book.short_description %></p>
                </td>
                <td class="price"><%= number_to_currency(item.price) %></td>
                <td><%= number_field_tag('quantity['+item.id.to_s+']', item.quantity, {:min => 1, :max => 20, :class => 'form-control quantity'}) %></td>
                <td class="price"><%= number_to_currency(item.price*item.quantity) %></td>
                <td class="price remove"><%= link_to('&times;'.html_safe, item_cart_path(item.id), {:method => 'delete'}) %></td>
            </tr>
            <%- end %>
            </tbody>
        </table>
        <div class="clearfix">
            <div class="subtotal pull-right">SUBTOTAL: &nbsp; <strong>$<%= @order.total_price %></strong></div>
        </div>
        <div class="form-inline pull-right">
            <!--<input type="text" class="form-control" placeholder="Coupon code" size="12">-->
            <%= submit_tag('UPDATE', :class => 'btn btn-default') %>
            <%= link_to('CHECKOUT', checkout_path(:address), :class => 'btn btn-default') %>
        </div>
        <%= link_to('EMPTY CART', cart_path, {:class => 'btn btn-default', :method => 'delete'}) %>
        <%= link_to('CONTINUE SHOPPING', shop_path, {:class => 'btn btn-default'}) %>
        <%- end %>
    <%- else %>
        <p>Shopping cart is empty&hellip; <%= link_to 'Get started shopping!', shop_path %></p>
    <%- end %>
</div>