config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/sign-up' => 'devise/registrations#new'
    get  '/sign-in' => 'devise/sessions#new'
    get  '/sign-out' => 'devise/sessions#destroy'
  end

  root   'books#home'
  get    '/shop', to: 'books#index'
  get    '/shop/:category_id', to: 'books#index', as: 'shop_category'
  resources :books, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resource  :cart, only: [:create, :show, :update, :destroy] do
    delete ':item_id', action: 'remove_item', as: 'item', item_id: /[0-9]+/
  end
  resources :checkout, only: [:show, :update]
  resource  :user, only: [:edit, :destroy] do
    put 'address',  action: 'address'
    put 'email',    action: 'email'
    put 'password', action: 'password'
  end
  resources :orders, only: [:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'custom', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header>
    <div class="row">
      <div class="col-md-3 logo">The Bookstore</div>
      <div class="col-md-3">
        <%= link_to_unless_current('HOME', root_path) %> |
        <%= link_to_unless_current('SHOP', shop_path) %>
      </div>
      <div class="col-md-3 text-center">
        <i class="glyphicon glyphicon-shopping-cart"></i>
        <%= link_to_unless_current('CART', cart_path) %>: <%= cart_details %>
      </div>
      <div class="col-md-3 text-right">
        <% if user_signed_in? %>
            <%= link_to_unless_current 'Settings', edit_user_path %> |
            <%= link_to_unless_current 'Orders', orders_path %> |
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to_unless_current 'Sign up', sign_up_path %> |
            <%= link_to_unless_current 'Sign in', sign_in_path %>
        <% end %>
      </div>
    </div>
  </header>

  <div id="flash-message">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash-#{name}" %>
    <% end %>
  </div>

  <%= yield %>

  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2014&ndash;<%=Time.now.year %> Bookstore, Inc.</p>
  </footer>
</div>

</body>
</html>

app/views/layouts/rails_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main-container" class="container">
    <%= yield %>
</div>

</body>
</html>